services:
  node1:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-1
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node1:/root/.simapp
    ports:
      - "37657:26657"
      - "13717:1317"
      - "9490:9090"
      - "36656:26656"

  node2:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-2
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node2:/root/.simapp
    ports:
      - "37658:26657"
      - "13718:1317"
      - "9491:9090"
      - "36657:26656"

  node3:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-3
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node3:/root/.simapp
    ports:
      - "37659:26657"
      - "13719:1317"
      - "9492:9090"
      - "36658:26656"

  node4:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-4
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node4:/root/.simapp
    ports:
      - "37660:26657"
      - "13720:1317"
      - "9493:9090"
      - "36659:26656"

  node5:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-5
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node5:/root/.simapp
    ports:
      - "37661:26657"
      - "13721:1317"
      - "9494:9090"
      - "36660:26656"

  node6:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-6
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node6:/root/.simapp
    ports:
      - "37662:26657"
      - "13722:1317"
      - "9495:9090"
      - "36661:26656"

  node7:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-7
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node7:/root/.simapp
    ports:
      - "37663:26657"
      - "13723:1317"
      - "9496:9090"
      - "36662:26656"

  node8:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-8
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node8:/root/.simapp
    ports:
      - "37664:26657"
      - "13724:1317"
      - "9497:9090"
      - "36663:26656"

  node9:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-9
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node9:/root/.simapp
    ports:
      - "37665:26657"
      - "13725:1317"
      - "9498:9090"
      - "36664:26656"

  node10:
    image: ghcr.io/cosmos/ibc-go-simd:release-v10.4.x
    container_name: chain-0-node-10
    command: >
      start
      --home /root/.simapp
      --rpc.laddr tcp://0.0.0.0:26657
      --grpc.address 0.0.0.0:9090
      --api.enable=true
      --p2p.laddr tcp://0.0.0.0:26656
    volumes:
      - ./chains/node10:/root/.simapp
    ports:
      - "37666:26657"
      - "13726:1317"
      - "9499:9090"
      - "36665:26656"

